name = "resist-events"
compatibility_date = "2024-12-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "RESIST_DB"
database_name = "resist-events-db"
database_id = "5c41278f-3275-4085-a4a0-837690bfc74c"
